### ISSUE TITLE
Show event counter in event tree view, activity tab

### ISSUE THREAD

**Issue by ianmstew** [marionettejs/marionette.inspector#138]
Show an incremented event count for each event in the tree view, floated right and greyed.  This will add to the scannable information.

**Comment by josephahn** [comment]
Now that the events for each action only get rendered when the toggle button is clicked, the action model doesn't know about its events on its initial render.

We could have the count render when the action is toggled, but I'm not sure that's the behavior you wanted @ianmstew 

I don't know if there are other workarounds for this apart from another refactor. Any ideas @jasonLaster ?

**Comment by ianmstew** [comment]
Hey @josephahn.

Ahh, I believe Jason and I considered incrementing the event counter at the source ([patchAppComponentTrigger](https://github.com/marionettejs/marionette.inspector/blob/master/extension/js/agent/patches/patchAppComponentTrigger.js#L33-L43)), then decided it was best counted on the view side.  But considering the extra processing that would take on the front end, I think it would be simplest to handle it on the data side, then it's just a model attribute.

We could either add a new counter to the data similar to the event id but without the preceding "e", or you could strip the "e" off on the front end and use that.  I think a new counter would be technically preferable because event id doesn't necessarily imply a counter, even though the implementation uses one.  @jasonLaster, thoughts?

**Comment by jasonLaster** [comment]
I think we can do something like this. When create action 1 we count action 0, when we create 2 we count 1. 

We can count by looking in the collection for all of the events that have that id right?

**Comment by ianmstew** [comment]
Ahh, I think we're talking about two different things.  I was talking about a count for each event, and I think you're talking about an aggregate count for each action, or possibly for each expander.  Now that I'm looking at the actual activity pane, I am seeing an incrementing event count for each event.  Since that's my understanding of this ticket, I think we can mark it closed.  See numbers 1, 2, 3, 4, etc in the screenshot:

![screen shot 2015-03-10 at 10 05 26 am](https://cloud.githubusercontent.com/assets/4119765/6576409/697e3d02-c70d-11e4-853b-12b839823644.png)

Speaking of this screenshot, it seems like the indents are off (new ticket?)
