### ISSUE TITLE
Needs a logo

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionette.inspector#146]
perhaps the M with a :mag: on top?

**Comment by nerdpruitt** [comment]
Here are my main two concepts. A quick note on these is that the vectors aren't really very finished. Just trying to get enough detail to get my ideas across and all that jazz :musical_score: 

The first one is kind of similar to one of Joanne's, which is to enclose an M in the magnifying glass. I’m not going straight up with the Marionette M though. Basically, the idea here is if you take a shape and cut three triangles out of it, you have an M! So I let the M fill the whole thing. I think it will scale well this way (though for something as small as, say, a favicon we'll still do some custom-ultra-zoomed-in-pixel-finessing). Plus it’s just kind of interesting to play with. :smiley: I think we could deviate and make it pretty different than the main Marionette logo M, or we could make it look related. I just threw a bunch in here to show the kind of stuff we could do.

![marionette-logo-concept1](https://cloud.githubusercontent.com/assets/1902312/5623684/4d76819a-951d-11e4-9f3f-04416c880f4b.png)

Full size: https://dl.dropboxusercontent.com/u/1480767/marionette-logo-concept1.png

And the second one is maybe a more literal take, where we make a tiny Chrome browser window and have it inspecting the Marionette M...meaning to represent a Marionette app. We could maybe even add more detail to the dev tools sidebar, but would have to be careful not to let it get too busy. This scaled better than I thought it would, but I think we'd drop the dev tools sidebar at smaller sizes for it to be more legible.

![marionette-logo-concept2](https://cloud.githubusercontent.com/assets/1902312/5623694/92555282-951d-11e4-8224-3f6c3a32a57b.png)

Full size: https://dl.dropboxusercontent.com/u/1480767/marionette-logo-concept2.png

**Comment by samccone** [comment]
woah the second batch i realllllly like

**Comment by nerdpruitt** [comment]
Working with concept 2 more. I added the dots and was able to make it a square instead of widescreen as a result!

![marionette-logo-concept2 1](https://cloud.githubusercontent.com/assets/1902312/5637114/dac3812e-95bd-11e4-93e0-6b31caf17ea3.png)

https://dl.dropboxusercontent.com/u/1480767/marionette-logo-concept2.1.png

**Comment by samccone** [comment]
:)

**Comment by jdaudier** [comment]
@nerdpruitt how does it look with the tabs removed (replaced with a straight line)?

**Comment by jasonLaster** [comment]
@nerdpruitt let's use what you've got! 
My last comment was really  minor stuff. 

Mind uploading the raw file.

**Comment by joshbedo** [comment]
I like these a lot! Great job @jdaudier and @nerdpruitt

**Comment by jdaudier** [comment]
thanks @joshbedo!

**Comment by nerdpruitt** [comment]
@jasonLaster would you want add the logo file to the repo somewhere in particular? 

Still want to work in the latest feedback from you and @jdaudier too...but I think it's cool to use it and we'll just keep improving the thing. :smiley:

**Comment by jasonLaster** [comment]
Yea. Let's put it in extensions/imgs 

And yea we can keep making it better.

**Comment by nerdpruitt** [comment]
Here is this guy - https://github.com/marionettejs/marionette.inspector/pull/224

**Comment by jasonLaster** [comment]
:boom:

**Comment by samccone** [comment]
closing since we have one :+1:
