### ISSUE TITLE
Firefox port

### ISSUE THREAD

**Issue by yoshdog** [marionettejs/marionette.inspector#218]
Any chance of porting this across to the dev tools for FireFox?

**Comment by jasonLaster** [comment]
Yup. There are some people interested in the work. 

Ember set the bar with their adapter pattern so it's definitely possible. 

It's not a personal priority for me, so this will have to come from the team/community, but I'm happy to advise of course.

**Comment by yoshdog** [comment]
I can look into it, if you can point me in the right direction.

**Comment by jasonLaster** [comment]
Happy to Yosh.

Here's what ember basically does:
+ https://github.com/emberjs/ember-inspector/blob/master/ember_debug/adapters/chrome.js
+ https://github.com/emberjs/ember-inspector/blob/master/app/adapters/chrome.js
+ dist folders for each devtool app (chrome, firefox)... ours 

Here's a list of places that'd have to change:
After looking at the list, i think we could do some relatively small abstractions and maybe be okay. My hope would be that there are some similar firefox libraries that could be used so the architecture doesn't need to be upended in a big way.


```patch
diff --git a/extension/js/background.js b/extension/js/background.js
index 16ce210..03cb6b2 100644
--- a/extension/js/background.js
+++ b/extension/js/background.js
@@ -1,3 +1,6 @@
+// we need to use the firefox equivelant
+
+
 /*
  Note: the background is shared between the browser tabs, therefore it
  identifies the various panel communication ports by using the id of the
diff --git a/extension/js/inspector/client/inspectedPage.js b/extension/js/inspector/client/inspectedPage.js
index 2e21e07..7424c40 100644
--- a/extension/js/inspector/client/inspectedPage.js
+++ b/extension/js/inspector/client/inspectedPage.js
@@ -50,6 +50,7 @@ define([
         // The callback "onExecuted" is called with the function return value.
         // The method is implemented by using devtools.inspectedWindow.eval.
         this.execFunction = function(func, args, onExecuted, context) {
+            // this needs to switch
             chrome.devtools.inspectedWindow.eval(serializeFunc(func, args, context), function(result, isException) {
                 if (isException) {
                     var error = _.isObject(isException) ? isException.value : result;
diff --git a/extension/js/inspector/panelPort.js b/extension/js/inspector/panelPort.js
index f1b332c..3ca44b4 100644
--- a/extension/js/inspector/panelPort.js
+++ b/extension/js/inspector/panelPort.js
@@ -1,6 +1,8 @@
 define([], function() {
     // Establish a bidiretional communication port with the background
     var tabId = chrome.devtools.inspectedWindow.tabId;
+
+    // this needs to be abstracted
     var panelPort = chrome.extension.connect({name: "devtoolspanel"});
 
     panelPort.postMessage({
diff --git a/extension/js/marionette_contentscript.js b/extension/js/marionette_contentscript.js
index b6d44ef..79769d6 100644
--- a/extension/js/marionette_contentscript.js
+++ b/extension/js/marionette_contentscript.js
@@ -1,3 +1,4 @@
+// we need to use the firefox equivelant here...
 var port = chrome.runtime.connect({
     name: 'contentscript'
 });
```

**Comment by Anachron** [comment]
@jasonLaster @yoshdog so how is it going here? Would be interested in a Firefox port too. I could be tester, I've got a Ubuntu 14.04 setup on x64.

**Comment by jasonLaster** [comment]
Hey @Anachron. Nothing yet. Still waiting for someone to pick it up

**Comment by paulfalgout** [comment]
https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/ :boom: :confetti_ball: :cake:

**Comment by maxlath** [comment]
the [`devtools.panels` API just arrived with Firefox 54](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/devtools.panels#Browser_compatibility), so this issue should now be (almost) trivial.

Installation instructions:
```
1. go to the URL `about:debugging#addons`
2. check "Activate modules debugging"
3. click the "Load a temporary module" and select the extension folder in the repo
```

Unfortunately, after installation, a few issue remain:
* `chrome.extension.onConnect` (used in [`background.js`](https://github.com/marionettejs/marionette.inspector/blob/master/extension/js/background.js#L11)) seems to have become `chrome.runtime.onConnect`, and while Chrome seem to have kept `chrome.extension.onConnect` for legacy support, Firefox doesn't know about it.
* once the previous issue is fixed and the addon rebuilt, opening dev tools does display a `Marionette` tab, but clicking it fails to display anything else than a gray background: it seems that some resources are blocked by CSP policies:
```
Content Security Policy: The page's settings blocked the loading of a resource at self (« script-src moz-extension://1ca85538-5622-4d5f-9048-36db41ccf4ee »). Source: onsubmit attribute on DIV element. panel.html
Content Security Policy: The page's settings blocked the loading of a resource at self (« script-src moz-extension://1ca85538-5622-4d5f-9048-36db41ccf4ee »). Source: onchange attribute on DIV element. panel.html
Content Security Policy: The page's settings blocked the loading of a resource at self (« script-src moz-extension://1ca85538-5622-4d5f-9048-36db41ccf4ee »). Source: onfocusin attribute on DIV element.
```

**Comment by captainbrosset** [comment]
I see this is closed, which is great! Are there any plans to upload the extension to addons.mozilla.org, so that it can be used in both Chrome and Firefox?
