### ISSUE TITLE
Can't see LayoutView regions

### ISSUE THREAD

**Issue by paulguz** [marionettejs/marionette.inspector#230]
Hi, I've just started using the Marionette Inspector and am still a noob when it comes to Backbone & Marionette.  I am using the latest version of the inspector from the Chrome Store as of the time of writing.

According to the Marinoette docs, use of Application Regions is deprecated.

http://marionettejs.com/docs/v2.3.2/marionette.application.html#application-regions

>Warning: deprecated This feature is deprecated. Instead of using the Application as the root of your view tree, you should use a Layout View. 

I am using a Layout View to manage my regions, but the regions within do not show in the UI tab.  Does the Marionette inspector support use of LayoutViews?  Do I need to do something with my LayoutView to make its regions appear in the inspector?

**Comment by jasonLaster** [comment]
@paulguz this should help https://github.com/marionettejs/marionette.inspector/blob/master/extension/js/agent/actions/appObserver.js#L49-L56

sorry for the confusion
