### ISSUE TITLE
Custom ItemView, using BabySitter - any way to instrument?

### ISSUE THREAD

**Issue by bazineta** [marionettejs/marionette.inspector#233]
We have a dashboard (essentially, drag and drop widget manager) view that's an ItemView, using a babysitter instance to manage subviews.  In short, it acts like a CompositeView, but isn't one.

The inspector doesn't find any of the managed subviews, presumably because it wouldn't look below an ItemView.  Is there any way to instrument this particular view, i.e., indicate to the inspector that it's got children?

**Comment by jasonLaster** [comment]
this is what we use to build the tree: https://github.com/marionettejs/marionette.inspector/blob/master/extension/js/agent/actions/regionInspector.js

Would be great to add hooks for additional view types

**Comment by bazineta** [comment]
The short answer here; if you have a view that uses a BabySitter instance, then simply name the BabySitter instance 'children', and it'll Just Work™.

**Comment by jasonLaster** [comment]
Haha thanks @bazineta. I'm sure there's a better story there. Thanks for getting to the bottom of this. 

P.S the magical thing to do in my mind is to look for BabySitter properties on the view and if they exist add the child nodes.

**Comment by jasonLaster** [comment]
@bazineta  mind adding this to the faq doc?
