### ISSUE TITLE
Inspector not finding Application

### ISSUE THREAD

**Issue by rsumilang** [marionettejs/marionette.inspector#236]
My app is built in requirejs and i use var App = new Marionette.Application(); inside a define() to create it. I tried debugging why the inspector is not working for me and i see that `window.__agent.patchedApplication` is empty however `both window.__agent.patchedBackbone` and `window.__agent.patchedMarionette` are working.

Please let me know what other things i can do to help the marionette inspector find my app.

![screen shot 2015-02-20 at 4 42 45 pm](https://cloud.githubusercontent.com/assets/1748115/6311904/978f02c2-b91f-11e4-9e4b-609afa0db0c9.png)

**Comment by jasonLaster** [comment]
Sure. Take a look at the developibg locally section and logs

**Comment by rsumilang** [comment]
@jasonLaster I attached a LayoutView to my application and now it's finding that and the view items below. I guess the confusion was because I was attaching itemviews directly to my app before while assuming the framework was less opinionated. Ty.

**Comment by samccone** [comment]
awesome @rsumilang if you think the documentation can be clarified please PR it up!

**Comment by jasonLaster** [comment]
Yup! We've also got a feature coming down the pipe for auto detecting view trees.
