### ISSUE TITLE
Plugin Crashes on old 2.0.0 Marionette applications 

### ISSUE THREAD

**Issue by mattbryson** [marionettejs/marionette.inspector#241]
Marionette.Behavior is not in 2.0.0, so need to check before patching it, else it crashes with

````bash
Uncaught TypeError: Cannot read property 'extend' of undefined
````

Had a quick go at fixing, but to no avail.

Changing patchMarionette.js to this kinda works...

````javascript

    this.patchMarionetteApplication(Marionette.Application);
    if(Marionette.Behavior) {
      this.patchMarionetteBehavior(Marionette.Behavior);  
    } 
    this.patchMarionetteModule(Marionette.Module);
    this.patchMarionetteController(Marionette.Controller);

    var marionetteClasses = [
      Marionette.Application.prototype, Marionette.Module.prototype,
      Marionette.Region.prototype, Marionette.Controller.prototype
    ];

    if (Marionette.Behavior) {
      marionetteClasses.push(Marionette.Behavior.prototype);
    }

    _.each(marionetteClasses, this.patchBackboneTrigger, this);
````

And then in knownTypes.js - only add Wreqr as a type if Wreqr.Channel exists (Radio is not in Wreqr in 2.0.0).
````javascript
//
    if(Agent.patchedBackbone.Wreqr.Channel) {
      _.extend(knownTypes, {
        'Backbone.Wreqr.Channel': {
          type: Agent.patchedBackbone.Wreqr.Channel,
          name: 'wreqr-channel',
          className: 'Wreqr.Channel',
          cid: function(obj) { return ''},
          toString: toString
        }
      });
    }
````

However, this gets stuck in some infinite loop and the inspector becomes un responsive.

**Comment by jasonLaster** [comment]
Thanks. I'm curious about the loop. It'd be nice to use the logging and turn on the lazy worker logs

**Comment by mattbryson** [comment]
Did some more digging this morning, it wasn't an infinite loop, it just hung for about a minute.

Turns out it was the console log that I put in which logged the Agent.knownTypes in the knownTypes function.  Took that out, and now it takes about 15 seconds, and then its running and appears ok.

It boots to just before the ' bb: Backbone loaded' log, then hangs for 10-15 seconds, and then comes back.

Out of interest, as the 2.0.0 doesn't have a Wreqr.Channel, would it work registering the Wreqr constructor function as the type?  Or is that not necessary ? (have only spent 10 mins looking at this project, so don't really know my way around yet).

Something like..
````javascript
 //Backbone 2.0 does not have Radio in Wreqr
    if (Agent.patchedBackbone.Wreqr) {
      if(Agent.patchedBackbone.Wreqr.Channel) {
        _.extend(knownTypes, {
          'Backbone.Wreqr.Channel': {
            type: Agent.patchedBackbone.Wreqr.Channel,
            name: 'wreqr-channel',
            className: 'Wreqr.Channel',
            cid: function(obj) { return ''},
            toString: toString
          }
        });
      } else {
        _.extend(knownTypes, {
          'Backbone.Wreqr': {
            type: Agent.patchedBackbone.Wreqr.__proto__.constructor,
            name: 'backbone-wreqr',
            className: 'Backbone.Wreqr',
            cid: function(obj) { return ''},
            toString: toString
          }
        });
      }
    }

````


I'll create a PR with what I have to date....
