### ISSUE TITLE
Activity "Action arrow is down" but nothing shows up

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/marionette.inspector#244]
When you go to Activity, show an activity tree, navigate to another tab and then come back, the action arrow is down, but the tree does not show up. 

![](http://f.cl.ly/items/1K2q2d0w3G3S1x2K0X3Y/Image%202015-03-02%20at%2010.40.35%20AM.png)

I think the easiest thing to do would be to wipe the slate, so that the arrow is up and everything is back to normal.

**Comment by samccone** [comment]
heh :+1:
