### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by pwdonald** [marionettejs/marionette.inspector#246]
When I start the Marionette Inspector in Chrome it triggers a seemingly infinite loop of errors in the console that print:

```Cannot read property 'length' of undefined Agent.js:18825```

Is this a problem with the inspector or my code?

**Comment by jasonLaster** [comment]
I think I've I've heard this before. Mind turning on the logs in local mode. The instructions are in the readme

**Comment by pwdonald** [comment]
I made some changes to my code (a lot) before I noticed your response. I turned on logs but the issue is no longer happening. I suspect my code was to blame.

**Comment by jasonLaster** [comment]
lolz glad it got sorted out.
