### ISSUE TITLE
Monitor inspector usage

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/marionette.inspector#255]
It'd be great to get client usage metrics

**Comment by samccone** [comment]
cc @meomix

**Comment by MeoMix** [comment]
https://github.com/MeoMix/StreamusChromeExtension/blob/Development/src/js/background/model/analyticsManager.js This is how I do analytics in Streamus. Works fine!

**Comment by samccone** [comment]
(cough pr) :heart:

**Comment by MeoMix** [comment]
You gotta setup a Universal Analytics account for inspector and give me the account ID and then I can drop this in :)

**Comment by samccone** [comment]
I think we can do that

**Comment by jasonLaster** [comment]
You both have access!

**Comment by jasonLaster** [comment]
Happy to pair at any point on this.

**Comment by samccone** [comment]
:art:

**Comment by jasonLaster** [comment]
Just added lib versions, and urls
