### ISSUE TITLE
Collect analytics about Mn usage

### ISSUE THREAD

**Issue by jmeas** [marionettejs/marionette.inspector#258]
How developers *use* Marionette is of particular importance to us, the developers of Marionette. Yet the direct line of communication that Github provides is at best an unrealized ideal; often we are left guessing at how people use Marionette.

The inspector gives an interesting opportunity for us to peek into people's applications and see how they're using them. Imagine wrapping the Module's constructor and reporting back on who is using Marionette.Module. That could be cool, huh?

One way this could be useful is that we could track how usage of a particular feature declines after a deprecation notice.

Just a thought :thought_balloon:

**Comment by jasonLaster** [comment]
Yup. good thinking @jmeas. This connects to #255, where we monitor how ppl use the inspector. Related, but different
