### ISSUE TITLE
Standalone/ static build needed

### ISSUE THREAD

**Issue by akshadddhoke** [marionettejs/marionette.inspector#259]
Can we add a link for a standalone packed/ unpacked build for Marionette inspector?
It will be useful for those not having access to Chrome webstore for installation.
Though the steps for building from source help, but it will be more convenient if we have a static build available for direct install.

**Comment by samccone** [comment]
:+1: great idea, good call, makes sense for enterprise networks where this is a real issue.

![](http://vignette4.wikia.nocookie.net/memoryalpha/images/4/40/Enterprise_firing_phaser_proximity_blast.jpg/revision/latest?cb=20120205211228&path-prefix=en)

**Comment by jasonLaster** [comment]
okee

**Comment by jasonLaster** [comment]
Just pushed a static zip: 
https://github.com/marionettejs/marionette.inspector/blob/master/extension.zip

After thinking about it, the easiest thing to do is to git clone and open the extension in chrome. Directions are in the readme, for working locally.

**Comment by akshaddhoke** [comment]
Thanks! That helps.
