### ISSUE TITLE
Link to source tap

### ISSUE THREAD

**Issue by kvslee** [marionettejs/marionette.inspector#271]
Hi, thanks for this awesome tool. When I click on method links in the Inspector, am I supposed to be led to Chrome Source tap automatically, right? Did I miss anything?

**Comment by jasonLaster** [comment]
nope - i'll investigate. seeing something as well

**Comment by kvslee** [comment]
Is this issue resolved? When I use the sample site, http://www.marionettewires.com/, the Inspector does not link to source tap automatically when I click any method. Thanks.
