### ISSUE TITLE
Agent.send() should use lazyWorker

### ISSUE THREAD

**Issue by ianmstew** [marionettejs/marionette.inspector#278]
Executing a deep `show()` cycle with Marionette.Inspector running revealed a long (500ms) "flat line" on the CPU profiler.  Closer inspection shows `agent.send()` to be 100% responsible for this flat line.  See below.

```js
    send: function() {
      // console.log('!!!! sending batch message')
      debug.log('postMessage sent ' + this.queue.length + ' messages.');
//       Agent.lazyWorker.send({
//         function: window.postMessage, 
//         context: window,
//         data: _.clone(this.queue)
//       })
      window.postMessage(this.queue, '*');
      this.queue = [];
    }
```

![screen shot 2015-04-13 at 5 44 25 pm](https://cloud.githubusercontent.com/assets/4119765/7126137/d6aaf55c-e204-11e4-8870-89bc834c0248.png)

**Comment by jasonLaster** [comment]
fixed

**Comment by ianmstew** [comment]
You nailed it.  Flatline gone; the same show cycle 1.3 seconds instead of 2.0.  Now that's money.

![screen shot 2015-04-13 at 7 18 58 pm](https://cloud.githubusercontent.com/assets/4119765/7127412/fd86158c-e211-11e4-8667-f97349a4a779.png)
