### ISSUE TITLE
breaking tests

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/marionette.inspector#282]
Fix the breaking tests introduced here
https://github.com/marionettejs/marionette.inspector/pull/281

**Comment by paulfalgout** [comment]
I think this is the intermittent tests failing.. something to do with lazyloader..  but it's not a specific test.. any test in the list can fail I think.  But often restarting that environment will fix it.

Not sure what is causing the problem.. Thought deleting the window.lazyLoader in afterEach was doing it, but that's gone and we are still seeing the issue.

But I don't think this is a new breaking test.  all passing after a selective restart.

**Comment by jasonLaster** [comment]
Thanks @paulfalgout - i bet we can play with the configuration times to get this right... Also a stub lazyWorker that's just not lazy... you know does the work synchronously
