### ISSUE TITLE
setElement will not generate UI tree correctly

### ISSUE THREAD

**Issue by berniezhao** [marionettejs/marionette.inspector#306]
I have a layoutView and regions inside.
If you use `this.getRegion('foo').show(subview)` or `this.showChildView('foo', subview)` the UI tree displays correctly.

However if my layoutView already has DOM and I use `subview.setElement(this.$('#foo))` the UI tree does not display the subview correctly.  It appears to be empty.

**Comment by berniezhao** [comment]
Using `this.getRegion('foo').attachView(subview)` solves the problem

**Comment by paulfalgout** [comment]
FWIW in Mn `v3` `.show` will act like `.attachView` if the view you're giving it is already rendered.

However.. that doesn't quite solve this case exactly because this isn't resolved yet: https://github.com/marionettejs/backbone.marionette/issues/2859

**Comment by berniezhao** [comment]
Yup I saw that thread.  There are quite indeed quite a few blocks of code that will only happen if render() happens.
