### ISSUE TITLE
Backbone and Marionette undefined

### ISSUE THREAD

**Issue by jekuno** [marionettejs/marionette.inspector#308]
I expose both Backbone and Marionette as globals named `window.Backbone` and `window.Marionette`. My Marionette application is globally exposed as `window.app`.

My application works fine. However as soon as starting the inspector I get errors such as:
`agent.js: Uncaught TypeError: Cannot read property 'prototype' of undefined` (running `BackboneComponent.prototype.initialize`)

or:
`Cannot read property 'Application' of undefined` (when running `window.app = new Marionette.Application()`)

I also tried setting the following without success:

```
if (window.__agent) {
  window.__agent.start(Backbone, Marionette);
}
```

Debugging the application shows:
`window.__agent.patchedMarionette` and `window.__agent.patchedBackbone` are set.

**However `window.__agent.patchedApp` is not set.**

Am I doing something wrong or is this a bug?

**Comment by gthieme** [comment]
I have the same issue. It was working fine before I updated Chrome. I created bug #307 Inspector stopped working with Chrome version 50.

**Comment by jekuno** [comment]
Thanks for the info. Then at least I can stop trying to fix my application ;)

**Comment by pascaldls** [comment]
Same problem will this be fixed

**Comment by blikblum** [comment]
Should be fixed in master, let me know otherwise

**Comment by jekuno** [comment]
I can confirm it works. Can we make a new release and push 0.7 to the Chrome Web Store?
