### ISSUE TITLE
Marionette.ItemView is undefined in Agent.js

### ISSUE THREAD

**Issue by aabanaag** [marionettejs/marionette.inspector#309]
<img width="876" alt="screen shot 2016-05-01 at 11 13 27 am" src="https://cloud.githubusercontent.com/assets/2245822/14939871/c4814518-0f8d-11e6-8ee9-cc8c80b98fbc.png">

<img width="478" alt="screen shot 2016-05-01 at 11 13 57 am" src="https://cloud.githubusercontent.com/assets/2245822/14939874/d29fd006-0f8d-11e6-8391-cf32c6a6e8d4.png">

I'm running Version 50.0.2661.94 (64-bit) of Chrome

**Comment by jekuno** [comment]
Probably related to #307 and #308.

**Comment by leroy0211** [comment]
This is related to Marionette version 3. 

`Marionette.ItemView` and `Marionette.LayoutView` have been removed and replace by `Marionette.View`


From their website:

> Note: From Marionette v3.x, Marionette.View replaces
Marionette.LayoutView and Marionette.ItemView.

**Comment by scott-w** [comment]
We currently haven't been able to upgrade Marionette Inspector to support v3. We're open to anyone looking to help with this effort.
