### ISSUE TITLE
Error on start "Cannot read property 'prototype' of undefined"

### ISSUE THREAD

**Issue by alex-shamshurin** [marionettejs/marionette.inspector#311]
in this line

```
 var initializeFncName = BackboneComponent.prototype.initialize ? 'initialize' : 'start';
```

possible a dublicate of #310

**Comment by vernondegoede** [comment]
Which version of Marionette are you using?

**Comment by alex-shamshurin** [comment]
2.4.7

**Comment by vernondegoede** [comment]
Could you paste your complete error trace?

**Comment by alex-shamshurin** [comment]
http://joxi.ru/E2pv6vZFBLexwr

**Comment by pgosk** [comment]
Same me. Not working

**Comment by vernondegoede** [comment]
Which Backbone version are you using? @pgosk @alex-shamshurin

**Comment by vernondegoede** [comment]
Could be related to #307 and #308 #309.

**Comment by pgosk** [comment]
@vernondegoede backbone marionette 2.4.7 from npm library

**Comment by pascaldls** [comment]
This bug was here since chrome 50 
worked fine before still not fixed please help 
https://github.com/marionettejs/marionette.inspector/issues/308

**Comment by alex-shamshurin** [comment]
So any updates?

**Comment by denar90** [comment]
Guys we will take care of inspector after v3 release. Sorry but all team is busy with it.

**Comment by jakejarrett** [comment]
Any updates on this now that v3 is out?

**Comment by lsimmons2** [comment]
Hello, I'm just starting to work with a big Marionette app that uses `marionette v2.4.7` and I'm getting this same error when starting the inspector.

Is there a way to use an older version of the inspector that will work with my app since upgrading to the current version of `marionette` ( `v.3.1.0` at the time of writing this) is unfeasible?

Thanks!

**Comment by lsimmons2** [comment]
Or I would consider upgrading for this. Is the inspector working for people who are using `backbone.marionette v3.1.0`?

**Comment by denar90** [comment]
Sorry guys, but we haven't done any progress to make it works. We will really appreciate your help with this issue.
Thanks.

**Comment by blikblum** [comment]
I'm looking into this.

After the first build it showed a similar issue, but i noticed that somehow the build changed the source files. After i reverted the changes and build again it worked.

I'm testing with MarionetteWires site. The errors you are spotting also occurs in MarionetteWires?

**Comment by blikblum** [comment]
I tested also the version published in Chrome history and is working with the MarionetteWires app

Is there any public app that is failing so i can trace the error?
