### ISSUE TITLE
Console errors when using marionette inspector - chrome updates breaking plugins?

### ISSUE THREAD

**Issue by redfox05** [marionettejs/marionette.inspector#312]
Update: I found that rather than using the toolbar, this plugin needs to be run from Chrome Inspector, and there is a Marionette tab from which you launch the plugin. However, once launched, the console is full of error messages (not application error messages).

Sounds like newer versions of Chrome may be breaking the plugin?

---

~~I installed the plugin successfully, but:~~

~~Every time I try to load the Marionette Inspector, the Chrome Plugin page for the plugin seems to load instead. Is this normal behaviour? Should I be loading the Plugin another way?~~

**Screenshots:**

Clicking on the plugin Icon and then 'Marionette Inspector':
<img width="264" alt="screen shot 2016-07-26 at 9 20 58 am" src="https://cloud.githubusercontent.com/assets/7571495/17146208/7000a2fe-5312-11e6-9024-8fb58b570b7a.png">

Which then shows this page:
<img width="1241" alt="screen shot 2016-07-26 at 9 21 24 am" src="https://cloud.githubusercontent.com/assets/7571495/17146227/79647852-5312-11e6-9292-6da4cac2c2c6.png">

**Comment by redfox05** [comment]
Update: I found that rather than using the toolbar, this plugin needs to be run from Chrome Inspector, and there is a Marionette tab from which you launch the plugin. However, once launched, the console is full of error messages (not application error messages).

Sounds like newer versions of Chrome may be breaking the plugin?

**Comment by barneydmedia** [comment]
Can confirm on both counts, the toolbar button is confusing to new users and on version 52.0.2743 of OSX Chrome I am having multiple console errors that prevent me from using the plugin.

**Comment by redfox05** [comment]
For now I am using the Backbone Chrome plugin, which seems to work. This Marionette one seems totally crashed with those errors. Seems strange not many have reported it?

**Comment by barneydmedia** [comment]
It looks like #311 is possibly related to this, and they noted on that issue that they will provide an update to this plugin, but all the core devs for this plugin are tied up working on Marionette v3 until it's released. 

Thanks for the tip about the Backbone plugin, I'll have to give that a shot until this team has more time for updates.

**Comment by johnmee** [comment]
I did the same thing first up, because we're trained to click on a logo when we see it.  But that's not the way to use this thing.  Right-click->Inspect and you should find a new `Marionette` tab.

![selection_008](https://cloud.githubusercontent.com/assets/660960/18572575/daa83ca0-7bff-11e6-8998-22ffcd99e673.png)

You also have to restart your tab first (although a browser restart wasn't necessary).

(And after all that I'm suffering [this issue](https://github.com/marionettejs/marionette.inspector/issues/311), so YMMV)

**Comment by blikblum** [comment]
master is working fine with recent Chrome. Please reopen if you find another issue with more details.
Regarding the usage, i think the docs can be improved
