### ISSUE TITLE
Wrong repo url

### ISSUE THREAD

**Issue by jekuno** [marionettejs/marionette.inspector#336]
Git clone with the provided URL doesn't work:

```
git clone git@github.com:marionettejs/marionette.inspector.git
Cloning into 'marionette.inspector'...
Permission denied (publickey).
fatal: Could not read from remote repository.
```

Fix it by using `git clone https://github.com/marionettejs/marionette.inspector.git`

**Comment by paulfalgout** [comment]
The `git@` works for me, but the other is just as good
