### ISSUE TITLE
Marionette inspector not working?

### ISSUE THREAD

**Issue by olhor** [marionettejs/marionette.inspector#339]
Version 0.8.0 seems not to work. After installation as Chrome extension the "Marionette" tab is blank. I checked it with sample app "Marionette Wires" but in other apps it is also not working. No information, no message, no nothing, just the blank "Marionette" tab.
I checked it in Chrome  58.0.3029.110 (64-bit) and Chromium 58.0.3029.96 (64-bit).
Btw. the Backbone Debugger works fine.

**Comment by blikblum** [comment]
What OS?
Any console message?

**Comment by olhor** [comment]
Didn't think about it... Does not work under Linux openSUSE 42.2 and no console messages appear but checked it under Windows 10 and there it works fine. Maybe something OS specific. Are there any special prerequisites for Linux?

**Comment by blikblum** [comment]
Probably related to https://github.com/marionettejs/marionette.inspector/pull/338

Will prepare a new release asap

**Comment by olhor** [comment]
I checked the version 0.8.1 and all seems to work under openSUSE 42.2. Thanks.
