### ISSUE TITLE
firefox add-ons link at readme.md broken

### ISSUE THREAD

**Issue by birbilis** [marionettejs/marionette.inspector#366]
Is there a firefox addon at all?
How about an Edge extension, those are like Chrome's, I think there is even a tool that can repackage a chrome extension for Edge to then put in windows store

**Comment by paulfalgout** [comment]
If I remember correctly I think the firefox extension store wanted a bunch of changes.  I don't remember exactly.  At some point it'd be nice to follow up on that.. But anyone who wants to make an Edge extension is welcome!

**Comment by blikblum** [comment]
> If I remember correctly I think the firefox extension store wanted a bunch of changes

For some time it was published on store but the reviewer asked to remove eval usage.

I will try to look at it.

@paulfalgout can you review #365 . It makes easier to update the codebase since we can start using ES6 features

**Comment by blikblum** [comment]
Its fixed now
