### ISSUE TITLE
Inspector continually throws `cid` error

### ISSUE THREAD

**Issue by cpjolicoeur** [marionettejs/marionette.inspector#54]
The inspector just continually throws the following error after the page has loaded.  A new error is thrown every millisecond continually.

![](https://dl.dropboxusercontent.com/spa/5649sdttrqrua6c/co4y1fgg.png)

**Comment by samccone** [comment]
has this been resolved @cpjolicoeur ?

**Comment by cpjolicoeur** [comment]
as far as I can tell.

**Comment by samccone** [comment]
wooot thanks @cpjolicoeur 

![](http://taco.jpg.to/)
